# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("background-color: rgb(239, 239, 239);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_x = QtWidgets.QFrame(self.centralwidget)
        self.line_x.setGeometry(QtCore.QRect(100, 250, 600, 3))
        self.line_x.setMinimumSize(QtCore.QSize(0, 0))
        self.line_x.setStyleSheet("\n"
                                    "background-color: rgb(0, 0, 0);")
        self.line_x.setLineWidth(1)
        self.line_x.setMidLineWidth(0)
        self.line_x.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_x.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_x.setObjectName("line_x")

        self.line_y = QtWidgets.QFrame(self.centralwidget)
        self.line_y.setGeometry(QtCore.QRect(400, 100, 3, 300))
        self.line_y.setMouseTracking(True)
        self.line_y.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_y.setLineWidth(2)
        self.line_y.setMidLineWidth(0)
        self.line_y.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_y.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_y.setObjectName("line_y")

        self.spinBox_d = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_d.setGeometry(QtCore.QRect(200, 0, 50, 30))
        self.spinBox_d.setMaximum(60)
        self.spinBox_d.setObjectName("spinBox_d")

        self.spinBox_F = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_F.setGeometry(QtCore.QRect(200, 30, 50, 30))
        self.spinBox_F.setMaximum(60)
        self.spinBox_F.setObjectName("spinBox_F")

        self.label_d = QtWidgets.QLabel(self.centralwidget)
        self.label_d.setGeometry(QtCore.QRect(0, 0, 200, 30))
        self.label_d.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 150, 150, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_d.setTextFormat(QtCore.Qt.AutoText)
        self.label_d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d.setObjectName("label_d")

        self.label_F = QtWidgets.QLabel(self.centralwidget)
        self.label_F.setGeometry(QtCore.QRect(0, 30, 200, 30))
        self.label_F.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 150, 150, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_F.setAlignment(QtCore.Qt.AlignCenter)
        self.label_F.setObjectName("label_F")

        self.label_3_dont = QtWidgets.QLabel(self.centralwidget)
        self.label_3_dont.setGeometry(QtCore.QRect(95, 253, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3_dont.setFont(font)
        self.label_3_dont.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3_dont.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3_dont.setObjectName("label_3_dont")

        self.label_4_dont = QtWidgets.QLabel(self.centralwidget)
        self.label_4_dont.setGeometry(QtCore.QRect(685, 253, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4_dont.setFont(font)
        self.label_4_dont.setObjectName("label_4_dont")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(391, 100, 20, 3))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(391, 400, 20, 3))
        self.line_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.label_1_dont = QtWidgets.QLabel(self.centralwidget)
        self.label_1_dont.setGeometry(QtCore.QRect(240, 253, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1_dont.setFont(font)
        self.label_1_dont.setObjectName("label_1_dont")

        self.label_2_dont = QtWidgets.QLabel(self.centralwidget)
        self.label_2_dont.setGeometry(QtCore.QRect(540, 253, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2_dont.setFont(font)
        self.label_2_dont.setObjectName("label_2_dont")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(325, 253, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(475, 253, 20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 70, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "app_lens"))
        self.label_d.setText(_translate("MainWindow", "Расстояние от предмета до линзы"))
        self.label_F.setText(_translate("MainWindow", "Фокусное расстояние"))
        self.label_3_dont.setText(_translate("MainWindow", "60"))
        self.label_4_dont.setText(_translate("MainWindow", "60"))
        self.label_1_dont.setText(_translate("MainWindow", "30"))
        self.label_2_dont.setText(_translate("MainWindow", "30"))
        self.label.setText(_translate("MainWindow", "15"))
        self.label_2.setText(_translate("MainWindow", "15"))
        self.pushButton.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
